### ISSUE TITLE
Deepsort Notebook not working

### ISSUE THREAD

**Issue by FritzTheBat** [tugstugi/dl-colab-notebooks#13]
When running the Deepsort Notebook I get:

> ModuleNotFoundError: No module named 'YOLO3'

not sure how the system path stuff that enables 
`from YOLO3 import YOLO3`
works, but that's probably where the error comes from.

**Comment by tugstugi** [comment]
should be fixed by 71a0ee6259f05cbe7a0f0ad53332269448365e62

**Comment by FloWuenne** [comment]
I am unfortunately still not able to run the Deepsort Notebook. 

I am getting the following error now:
`ModuleNotFoundError: No module named 'YOLOv3'`

I don't really see how we are able to import Yolov3 in this session, since we never installed or loaded it?!

Thanks for the help and the great notebook!

**Comment by FloWuenne** [comment]
Update

For anyone trying to run the notebook in 2020 and running into the same issue. It seems that the architecture of the deep_sort_pytorch repo significantly changed. To be able to run the notebook now, you have to use the specific version of the repo from July 2019. 

Adding this to the notebook after cloning the deep_sort_pytorch made it work without a problem for me:

`%cd "./deep_sort_pytorch"`
`!git checkout aa8347b73a`
`%cd /..`

**Comment by tugstugi** [comment]
@FloWuenne I have updated the notebook to the newest version: f9cd1a971218975bbee5782633ee7f83a3071a91

Greetings
